-- INSERT INTO bike_type
-- VALUES
--     ('1', '2 wheels');
-- INSERT INTO bike_type
-- VALUES
--     ('2', '3 wheels');
-- INSERT INTO bike_type
-- VALUES
--     ('3', '4 wheels');

-- INSERT INTO student
--     (student_id,username,password,name,bachelor)
-- VALUES
--     ('1', 'pontep', 'asdasd', 'Pontep Thaweesup', 'Computer Engineering');
-- INSERT INTO student
--     (student_id,username,password,name,bachelor)
-- VALUES
--     ('2', 'kettiya', '123456', 'Kettiya Muangkeaw', 'Aeroneutical Engineering');
-- INSERT INTO student
--     (student_id,username,password,name,bachelor)
-- VALUES
--     ('3', 'admin', 'admin', 'Administrator', 'Teacher');
